# Custom branding configuration
location = /custom-branding.js {
    alias /config/custom-branding.js;
}

location = /custom-branding.css {
    alias /config/custom-branding.css;
}

sub_filter "</head>" "<link rel=\"stylesheet\" href=\"/custom-branding.css\"><script src=\"/custom-branding.js\"></script></head>";
sub_filter_once off;
sub_filter_types text/html;
